name: ChatControl
version: 1.0
main: com.github.mcvier3ck.chatcontrol.ChatControlMain
author: McVier3ck
website: https://github.com/McVier3ck

commands:
  chatcontrol:

permissions:
  chatcontrol.*:
    children:
      chatcontrol.add: true
      chatcontrol.remove: true
      chatcontrol.list: true
      chatcontrol.morewords: true
  chatcontrol.add:
    default: op
  chatcontrol.remove:
    default: op
  chatcontrol.list:
    default: op
  chatcontrol.morewords:
    default: op

